.TH "binfmtc" 1 "2005 May 3" "binfmt_misc Dancer" "binfmt_C"
.SH NAME
binfmtc-interpreter \- binfmt_misc C handler
.SH SYNOPSIS
.BI "binfmtc-interpreter " "C-source-file-name" " [" "command-line opions ..." "]"
.SH "DESCRIPTION"
.B "binfmtc-interpreter"
compiles a C source file specified on the command-line using 
C compiler, and executes the resulting file.

It is designed to be used as a handler for 
.B "binfmt_misc"
handler, which is a system used in Linux for handling arbitrary files 
as executables.

The command-line options are passed on to the 
compiled binary.

.SH "FILE MAGIC"

There is a requirement for C source files to have the 
magic characters
.B "/*BINFMTC:"
at the beginning of the file.

That line also is used to specify the additional command-line options
for C compiler.

.SH "ENVIRONMENT"
.TP
.B "GCC"
The compiler used.
The default is to use
.B "gcc"

.TP
.B "CC"
The compiler used, if 
.B "GCC"
variable is not set.

.TP
.B "BINFMTCTMPDIR"

Temporary directory used for binary and execution.

Falls back to 
.B "$TMPDIR" 
.B "$TEMPDIR"
or
.B "/tmp"

.TP
.B "BINFMTC_DEBUG"
enables debug output if set.

.TP
.B "BINFMTC_GCC_OPTS"
Additional GCC options.
Use 
.B "BINFMTC_DEBUG"
to verify the options being passed on to gcc.

The default is
.B " -O2 -Wall "

.SH "AUTHOR"
Junichi Uekawa (dancer@debian.org)

Upstream page is available at 
.B "http://www.netfort.gr.jp/~dancer/software/"

.SH "SEE ALSO"
.BR "binfmtcxx-interpreter" "(1)" 
