.TH "binfmtasm" 1 "2005 May 3" "binfmt_misc Dancer" "binfmt_C"
.SH NAME
binfmtasm-interpreter \- binfmt_misc Assembly handler
.SH SYNOPSIS
.BI "binfmtasm-interpreter " "Assembly-source-file-name" " [" "command-line opions ..." "]"
.SH "DESCRIPTION"
.B "binfmtasm-interpreter"
compiles an assembly source file specified on the command-line using 
gas compiler, and executes the resulting file.

It is designed to be used as a handler for 
.B "binfmt_misc"
handler, which is a system used in Linux for handling arbitrary files 
as executables.

The command-line options are passed on to the 
compiled binary.

.SH "FILE MAGIC"

There is a requirement for C++ source files to have the 
magic characters
.B "/*BINFMTASMCPP:"
at the beginning of the file.

That line also is used to specify the additional command-line options
for the assmebler.

.SH "ENVIRONMENT"
.TP
.B "GAS"
The compiler used.
The default is to use
.B "gcc"

.TP
.B "AS"
The compiler used, if 
.B "GAS"
variable is not set.

Will fall back to using
.B "GCC"
and 
.B "CC"

.TP
.B "BINFMTCTMPDIR"

Temporary directory used for binary and execution.

Falls back to 
.B "$TMPDIR" 
.B "$TEMPDIR"
or
.B "/tmp"

.TP
.B "BINFMTC_DEBUG"
enables debug output if set.

.TP
.B "BINFMTASM_GAS_OPTS"
Additional G++ options.
Use 
.B "BINFMTC_DEBUG"
to verify the options being passed on to g++.

The default is 
.B " -O2 -Wall "

.SH "AUTHOR"
Junichi Uekawa (dancer@debian.org)

Upstream page is available at 
.B "http://www.netfort.gr.jp/~dancer/software/"

.SH "SEE ALSO"
.BR "binfmtc-interpreter" "(1), " 
.BR "binfmtcxx-interpreter" "(1), "
.BR "binfmtf-interpreter" "(1), "
.BR "binfmtf95-interpreter" "(1), "
.BR "binfmtgcj-interpreter" "(1), "
.BR "binfmtp-interpreter" "(1)"
