.TH "realcsh" 1 "2007 Jan 13" "binfmt_misc Dancer" "binfmt_C"
.SH "NAME"
realcxxsh.c \- A shell for running C++ code
.SH "SYNOPSIS"
.BI "realcxxsh.c [" "g++ options" "]"
.SH "DESCRIPTION"
.B "realcsh.c"
is an interactive shell that runs C++ source code.
A line of input is handled as a line in
.B "main()"
function, and the resulting C++ code is compiled, and executed.

If a line starting with
.B "#"
such as 
.B "#include <iostream>"
is entered, it is added to every code after that
at the start of sourcecode.

The list of such lines can be seen with
.B "##"

.SH "EXAMPLES"

The following is an example session

.nf
$ ./realcxxsh.cc 
REAL c++sh: cout << "Hello world\n"; 
Hello world
REAL c++sh: system ("pwd"); 
/home/dancer
REAL c++sh: 
.hy

.SH "INTERNALS" 
The following is how the C code looks like.

.nf
/*BINFMTCXX:
*/
#include <iostream>

int main(int argc, char ** argv)
{
.I "input-line"
return 0;
}
.hy

.SH "AUTHOR"
Junichi Uekawa (dancer@debian.org)

Upstream page is available at 
.B "http://www.netfort.gr.jp/~dancer/software/"

.SH "SEE ALSO"
.BR "binfmtc-interpreter" "(1)," 
.BR "realcsh.c" "(1), " 
.BR "realksh.c" "(1)" 
